### PR TITLE
solves #122

### LINKED ISSUE #122: Build fails if unsupported versions of OpenCV are present
If an older version like 2.4.8 is installed alongside newer supported version, then in some cases cmake may find older versions and throw a error subsequently.
Have a look at [this file](https://github.com/JdeRobot/dl-DetectionSuite/blob/master/DeepLearningSuite/Deps/opencv/CMakeLists.txt).

### PR DESCRIPTION
**Pull request by sleep-404**
Fixes #122

### CODE REVIEW

**Comment by vinay0410** [comment]
Hi @sleep-404 ,
What if user has OpenCV 4.2.0-dev (hypothetically) installed alongside OpenCV 4.0, and 4.2.0-dev isn't supported at that time.
I mean to say the latest available version may not be supported all the time. One should start search from minimum required version and then go above.

**Comment by sleep-404** [comment]
Actually that is exactly what it does.
The `ASC` tag returns versions starting from the least available version until the version condition is satisfied.
I had 3.6 installed along with 4.0, and the version loaded was 3.6 only.
Although you could test it once before merging , just to be sure.

**Comment by vinay0410** [comment]
Okay, great !!

Let me just test it, and then I will merge

**Comment by sleep-404** [comment]
is it working as expected ?

**Comment by sleep-404** [comment]
@vinay0410  , is it working as expected ?

**Comment by vinay0410** [comment]
Hi @sleep-404 ,
When OpenCV 4.1 and OpenCV 3.4 are installed side by side, it chooses 4.1 rather than 3.4.
Is this the expected functionality ?
Always try after deleting or cleaning your build directory, since find package generally caches previously found packages

**Pull request closed without merging**
